source /etc/bash_completion

SSH_AGENT_FILE=~/.ssh-agent.env

if [[ -f $SSH_AGENT_FILE ]]; then
    cat $SSH_AGENT_FILE | eval
fi

if [[ ! -z $SSH_AGENT_AUTH_SOCK ]]; then
    ARGS=`ssh-agent`
    eval $ARGS
    echo $ARGS > $SSH_AGENT_FILE
    ssh-add ~/.ssh/id_rsa

    pushd ~/.dotfiles >/dev/null
    git pull origin master &&
    bash ~/.dotfiles/extract.sh
    popd >/dev/null
fi


